import type { Metadata } from "next";
import "./globals.css";
import ReduxProvider from "@/redux/provider";
// import { Header } from "@/components/layout/header";
import AlgoliaClient from "@/helper/algoliaSearch";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AlgoliaClient>
        <ReduxProvider>
       {children}</ReduxProvider>
        </AlgoliaClient>
      </body>
    </html>
  );
}
